Add various AdapterActions
BHoM/MidasCivil_Toolkit pull request #265
Opened 2020-11-06 23:31 UTC by peterjamesnugent

### Issues addressed by this PR

Closes #264 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/ErxmGOmmN8NBgJlqNkc3AbYBeORcs5tkjRCKIUEbgCxQJQ?e=sAdf2k

### Changelog

- Added `AdapterActions` such as `NewModel`, `OpenFile`, `SaveAs` and `ClearResults`
- Migrated the expected directory for results to `m_directory\Results` similar to where TextFiles are stored (`m_directory\TextFiles`)
- This allows for the easy removal of the `Results` directory when invoking `ClearResults`
- When `NewModel` is invoked, the `Units` and `MidasCivilVersion` files (if available) will be copied, otherwise they will default SI Units and the default `MidasCivilVersion` which is currently `8.8.1`
- When `SaveAs` is invoked, all the files in the `\TextFiles` and `\Results\` folders will be copied over along with the `.mcb` and `.mct` file

### Additional comments

2020-11-08 16:03 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-08 16:03 UTC, FraserGreenroyd commented
@BHoMBot check documentation compliance

2020-11-08 16:03 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2020-11-08 16:04 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2020-11-10 16:50 UTC, ismaelibrahim requested changes
Script review:
- New model is created correctly
- "Save as" is also created with the unit and version text files copied over
- Geometry and loading is pushed successfully and is copied to the "Save as" model
- There is an issue when clearing results "The directory is not empty" (see attached photo
![PR review](https://user-images.githubusercontent.com/43822015/98704698-db752c80-2374-11eb-8dcd-0e33493e4fde.JPG)

2020-11-11 16:38 UTC, ismaelibrahim approved these changes
Everything works as it should with results now clearing.
Happy to approve.

2020-11-11 16:51 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-11 16:52 UTC, FraserGreenroyd commented
@BHoMBot check documentation compliance

2020-11-11 16:52 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2020-11-11 17:28 UTC, peterjamesnugent commented
@BHoMBot check installer

2020-11-11 17:52 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-11-11 21:44 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-11-11 21:56 UTC, peterjamesnugent commented
/azp run MidasCivil_Toolkit.CheckInstaller

2020-11-11 22:10 UTC, merged