Fix bug where *VERSION was not correctly set
BHoM/MidasCivil_Toolkit pull request #287
Opened 2021-01-19 13:03 UTC by peterjamesnugent

### Issues addressed by this PR

Closes #251 
Closes #286 

- Changed when a default `m_midasCivilVersion` was set 
- Made `m_midasCivilVersion` `public` so it is viewable from exploding the `Adapter`

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/MidasCivil_Toolkit/MidasCivil_Toolkit-%23286?csf=1&web=1&e=2xc3Iy

### Changelog

- Fixed a bug the `m_midasCivilVersion` was defaulting to 8.8.1 despite using an override within the adapter

2021-01-19 13:05 UTC, peterjamesnugent commented
@BHoMBot check all

2021-01-21 16:44 UTC, StephennipBH requested changes
Issue #286 has been resolved. All items have been tested. There is an issue with the 'SaveAs' command when the midas file is not blank. Please see below for the error message.
![image](https://user-images.githubusercontent.com/56433996/105382376-e9aeb700-5c07-11eb-8d6d-30b332c5bc6f.png)

2021-01-21 16:59 UTC, peterjamesnugent commented
@BHoMBot check all

2021-01-21 17:04 UTC, StephennipBH approved these changes
The bug in regards to *VERSION is fixed. The 'SaveAs' issue will be raised in a new issue

Changes Approved.

2021-01-21 17:52 UTC, peterjamesnugent commented
/azp run MidasCivil_Toolkit.CheckPR

2021-01-21 17:52 UTC, peterjamesnugent commented
/azp run MidasCivil_Toolkit.PR

2021-01-21 17:57 UTC, merged