Add support for pushing and pulling of custom sections
BHoM/MidasCivil_Toolkit pull request #355
Opened 2023-07-11 16:07 UTC by peterjamesnugent

### Issues addressed by this PR

Closes #332 

### Test files

[Push and pull](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23332%20Add%20Freeform%20Profiles?csf=1&web=1&e=TOnDcs)

### Changelog

Added support for pushing `FreeformProfile` 
Added support for pulling PSC-Value General sections

### Additional comments

~The Shear Factor for Shear Stress (Qby, Qbz) is not clear how to calculate it for PSC-Value sections - I have contacted Midas regarding this.~ Added calculation.
~The Asy and Asz is also different to what our integration method is calculation - so will need some testing.~ Will leave it based on integration methods.
~There is also a visual bug for plates at 40mm.~ Purely visual.

Tickets raised here:
https://globalsupport.midasuser.com/helpdesk/Ticket/61518403
https://globalsupport.midasuser.com/helpdesk/Ticket/61637483

2023-08-18 14:47 UTC, peterjamesnugent commented
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance
@BHoMBot check documentation-compliance
@BHoMBot check null-handling
@BHoMBot check serialisation

2023-09-04 12:49 UTC, StephennipBH requested changes
![image](https://github.com/BHoM/MidasCivil_Toolkit/assets/56433996/fc1d0946-f56a-4999-9d60-d7a0d8ba8e81)
![image](https://github.com/BHoM/MidasCivil_Toolkit/assets/56433996/34672af9-4ff0-4f50-aced-7503922ab095)

The pushing function is having error in the string ID format.
Regarding the pull function there is a problem with the index array

2023-09-05 18:47 UTC, StephennipBH approved these changes
Changes work as intended, changes approved

2023-09-05 21:00 UTC, peterjamesnugent commented
@BHoMBot check required

2023-09-06 13:56 UTC, jtrainor1 commented
When pushing custom sections and pulling them back in, they lose the Plastic Section Modulus values: 
![image](https://github.com/BHoM/MidasCivil_Toolkit/assets/111453218/7d7940c0-e7e0-47d0-9e2e-dc308c09092b)

2023-09-06 14:51 UTC, jtrainor1 commented
When I explode the pulled Generic objects, the plastic modulus doesn't show. However, when I explode the pulled Steel Sections the plastic modulus shows: 
![image](https://github.com/BHoM/MidasCivil_Toolkit/assets/111453218/7103c6c3-12eb-4a28-8817-9a8e3a9f08ab)
Potentially an issue with the BH.oM.Structure.SectionProperties.GenericSection BHoM object.

2023-09-06 19:05 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check copyright-compliance

2023-09-06 19:25 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-09-06 19:37 UTC, merged